# Generated by Django 3.2.6 on 2021-08-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_rename_files_multi_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi',
            name='image',
            field=models.FileField(upload_to='singledocs/multifiles/'),
        ),
    ]
